/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmecy_management;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author User
 */
public final class user_control extends javax.swing.JFrame {

    /**
     * Creates new form user_control
     */
    public user_control() {
        initComponents();
        medicine_name();
    }
    public ArrayList<customers> userList_1(){
        ArrayList<customers> usersList = new ArrayList<>();
        PreparedStatement ps;
        String query1 = "SELECT * FROM customer";
        try {
            ps = myconnection.getConnection().prepareStatement(query1);
            ResultSet rs = ps.executeQuery(query1);
            customers user;
            while(rs.next()){
                user = new customers(rs.getString("cust_name"),rs.getString("medicine_name"),rs.getString("quantity"),rs.getString("date_info"),rs.getString("price"));
                usersList.add(user);
            }
        } catch (SQLException ex) {
            Logger.getLogger(user_control.class.getName()).log(Level.SEVERE, null, ex);
        }
        return usersList;
    }
    public void show_info(){
        ArrayList<customers> list = userList_1();
        DefaultTableModel model = (DefaultTableModel)datatable.getModel();
        Object[] row = new Object[5];
        for(int i = 0;i < list.size();i++){
            row[0] = list.get(i).get_customer_name();
            row[1] = list.get(i).get_medicine_name();
            row[2] = list.get(i).get_quantity();
            row[3] = list.get(i).get_date();
            row[4] = list.get(i).get_price();
            model.addRow(row);
        }
    }
    public void medicine_price(){
        PreparedStatement ps;
        ResultSet rs;
        String mname = (String) medicine_name.getSelectedItem();
        int qnty = Integer.parseInt(quantity.getText());
        String query = "SELECT `price` FROM `medicine_information` WHERE `med_name` =?";
        try {
            ps  = myconnection.getConnection().prepareStatement(query);
            ps.setString(1, mname);
            rs = ps.executeQuery();
            if(rs.next()){
                int price = rs.getInt("price");
                int total_price = price * qnty;
                t_price.setText(String.valueOf(total_price));
            }
        } catch (SQLException ex) {
            Logger.getLogger(user_control.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Can't fetch!!");
        }
    }
    public void medicine_name(){
        PreparedStatement ps;
        ResultSet rs;
        String query = "Select med_name from medicine_information";
        try {
            ps = myconnection.getConnection().prepareStatement(query);
            rs = ps.executeQuery();
            while(rs.next()){
                medicine_name.addItem(rs.getString("med_name"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(user_control.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cust_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        medicine_name = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        date_choose = new datechooser.beans.DateChooserCombo();
        jButton1 = new javax.swing.JButton();
        count = new javax.swing.JButton();
        t_price = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        datatable = new javax.swing.JTable();
        show_btn = new javax.swing.JButton();
        clear_btn = new javax.swing.JButton();
        delete_btn1 = new javax.swing.JButton();
        back = new javax.swing.JButton();
        update = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Product Sell");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("X");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(451, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(393, 393, 393)
                .addComponent(jLabel7)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Customer Name:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 94, -1, -1));
        jPanel1.add(cust_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 217, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Medicine Name:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 125, -1, -1));

        jPanel1.add(medicine_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 217, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Quantity:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));
        jPanel1.add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 82, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 204, 204));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 10, 120));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Total Price:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 90, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Date:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        date_choose.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    date_choose.setFormat(0);
    jPanel1.add(date_choose, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 220, -1));

    jButton1.setBackground(new java.awt.Color(153, 153, 255));
    jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jButton1.setText("Insert");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });
    jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, -1));

    count.setBackground(new java.awt.Color(153, 153, 255));
    count.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    count.setText("Count");
    count.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            countActionPerformed(evt);
        }
    });
    jPanel1.add(count, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 170, -1, -1));

    t_price.setBackground(new java.awt.Color(153, 204, 255));
    t_price.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    jPanel1.add(t_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 120, 160, 30));

    datatable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "Customer Name", "Medicine Name", "Quantity", "Date", "Price"
        }
    ));
    datatable.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            datatableMouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(datatable);

    jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 1010, 160));

    show_btn.setBackground(new java.awt.Color(153, 204, 255));
    show_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    show_btn.setText("Show All");
    show_btn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            show_btnActionPerformed(evt);
        }
    });
    jPanel1.add(show_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, -1, -1));

    clear_btn.setBackground(new java.awt.Color(153, 204, 255));
    clear_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    clear_btn.setText("Clear");
    clear_btn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            clear_btnActionPerformed(evt);
        }
    });
    jPanel1.add(clear_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, -1, -1));

    delete_btn1.setBackground(new java.awt.Color(153, 204, 255));
    delete_btn1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    delete_btn1.setText("Delete");
    delete_btn1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            delete_btn1ActionPerformed(evt);
        }
    });
    jPanel1.add(delete_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, -1, -1));

    back.setBackground(new java.awt.Color(153, 204, 255));
    back.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    back.setText("Back");
    back.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            backActionPerformed(evt);
        }
    });
    jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 410, -1, -1));

    update.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    update.setText("Update Medicine Information");
    update.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            updateActionPerformed(evt);
        }
    });
    jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, -1, -1));

    getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

    setSize(new java.awt.Dimension(1004, 601));
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void countActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countActionPerformed
        medicine_price();
    }//GEN-LAST:event_countActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String customer_name = cust_name.getText();
        String med_name = (String) medicine_name.getSelectedItem();
        String qnty = quantity.getText();
        String date = date_choose.getText();
        String price = t_price.getText();
        String query = "INSERT INTO `customer`(`cust_name`, `medicine_name`, `quantity`, `date_info`, `price`) VALUES (?,?,?,?,?)";
        PreparedStatement ps;
        if(customer_name.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Customer Name FIrst!!");
        }
        else if(qnty.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Quantity First!!");
        }
        else if(price.equals("")){
            JOptionPane.showMessageDialog(null,"Press Count Button First");
        }
        else{
                try {
                ps = myconnection.getConnection().prepareStatement(query);
                ps.setString(1, customer_name);
                ps.setString(2, med_name);
                ps.setString(3, qnty);
                ps.setString(4, date);
                ps.setString(5, price);
                if(ps.executeUpdate() > 0){
                    JOptionPane.showMessageDialog(null, "Information Added Successfully!!!");
                }
            } catch (SQLException ex) {
                Logger.getLogger(user_control.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void show_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_btnActionPerformed
        show_info();
    }//GEN-LAST:event_show_btnActionPerformed

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
        cust_name.setText("");
        quantity.setText("");
        t_price.setText("");
        DefaultTableModel model = (DefaultTableModel)datatable.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_clear_btnActionPerformed

    private void delete_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btn1ActionPerformed
        String customer_name = cust_name.getText();
        PreparedStatement ps;
        String query = "";
        query = "Delete from customer where cust_name = ?";
        try {
            ps = myconnection.getConnection().prepareStatement(query);
            ps.setString(1, customer_name);
            if(ps.executeUpdate() > 0){
                JOptionPane.showMessageDialog(null,"Data Deleted Successfully");
            }
        } catch (SQLException ex) {
            Logger.getLogger(user_control.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_delete_btn1ActionPerformed

    private void datatableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datatableMouseClicked
        int i = datatable.getSelectedRow();
        TableModel model = datatable.getModel();
        cust_name.setText(model.getValueAt(i, 0).toString());
    }//GEN-LAST:event_datatableMouseClicked

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        pharma_login hreg = new pharma_login();
        hreg.setVisible(true);
        hreg.pack();
        hreg.setLocationRelativeTo(null);
        hreg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        PreparedStatement ps;
        ResultSet rs;
        String mname = (String) medicine_name.getSelectedItem();
        int qnty = Integer.parseInt(quantity.getText());
        int total_medicine;
        String query1 = "SELECT `med_quantity` FROM `medicine_information` WHERE `med_name` =?";
        String query2;
        try {
            ps  = myconnection.getConnection().prepareStatement(query1);
            ps.setString(1, mname);
            rs = ps.executeQuery();
            if(rs.next()){
                int number_of_med = rs.getInt("med_quantity");
                total_medicine = number_of_med - qnty;
                if(total_medicine > 0){
                    query2 = "Update medicine_information set med_quantity = ? where med_name = ?";
                    ps = myconnection.getConnection().prepareStatement(query2);
                    ps.setInt(1,total_medicine);
                    ps.setString(2, mname);
                    if(ps.executeUpdate() > 0){
                        JOptionPane.showMessageDialog(null, "Medicine Quantity Updated Successfully");
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null,"Medicine Out Off Stock!!!");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(user_control.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Can't fetch!!");
        }
    }//GEN-LAST:event_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user_control().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton clear_btn;
    private javax.swing.JButton count;
    private javax.swing.JTextField cust_name;
    private javax.swing.JTable datatable;
    private datechooser.beans.DateChooserCombo date_choose;
    private javax.swing.JButton delete_btn1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> medicine_name;
    private javax.swing.JTextField quantity;
    private javax.swing.JButton show_btn;
    private javax.swing.JTextField t_price;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
